import type { AchievementDefinition, MilestoneDefinition } from './types';

export const ACHIEVEMENT_CATALOGUE: AchievementDefinition[] = [
  {
    id: 'first-completion',
    title: 'First Check-In',
    description: 'Complete your first scheduled habit day.',
    tier: 'free',
    metric: 'totalCompletions',
    target: 1,
  },
  {
    id: 'five-completions',
    title: 'Five Day Momentum',
    description: 'Log five scheduled habit completions.',
    tier: 'free',
    metric: 'totalCompletions',
    target: 5,
  },
  {
    id: 'seven-completions',
    title: 'Seven Day Wins',
    description: 'Log seven scheduled habit completions.',
    tier: 'free',
    metric: 'totalCompletions',
    target: 7,
  },
  {
    id: 'fourteen-completions',
    title: 'Two Weeks Logged',
    description: 'Reach fourteen scheduled habit completions.',
    tier: 'free',
    metric: 'totalCompletions',
    target: 14,
  },
  {
    id: 'three-day-streak',
    title: 'Three Day Streak',
    description: 'Hold a three-day streak on any habit.',
    tier: 'free',
    metric: 'longestStreak',
    target: 3,
  },
  {
    id: 'seven-day-streak',
    title: 'Seven Day Streak',
    description: 'Hold a seven-day streak on any habit.',
    tier: 'free',
    metric: 'longestStreak',
    target: 7,
  },
  {
    id: 'fourteen-day-streak',
    title: 'Fourteen Day Streak',
    description: 'Hold a fourteen-day streak on any habit.',
    tier: 'free',
    metric: 'longestStreak',
    target: 14,
  },
  {
    id: 'three-scheduled-days',
    title: 'Three Active Days',
    description: 'Complete habits on three separate calendar days.',
    tier: 'free',
    metric: 'scheduledDays',
    target: 3,
  },
  {
    id: 'seven-scheduled-days',
    title: 'Seven Active Days',
    description: 'Complete habits on seven separate calendar days.',
    tier: 'free',
    metric: 'scheduledDays',
    target: 7,
  },
  {
    id: 'fourteen-scheduled-days',
    title: 'Fourteen Active Days',
    description: 'Complete habits on fourteen separate calendar days.',
    tier: 'free',
    metric: 'scheduledDays',
    target: 14,
  },
  {
    id: 'two-habits',
    title: 'Two Habits Active',
    description: 'Complete two different habits.',
    tier: 'free',
    metric: 'distinctHabits',
    target: 2,
  },
  {
    id: 'three-habits',
    title: 'Three Habits Active',
    description: 'Complete three different habits.',
    tier: 'free',
    metric: 'distinctHabits',
    target: 3,
  },
  {
    id: 'five-habits',
    title: 'Five Habits Active',
    description: 'Complete five different habits.',
    tier: 'free',
    metric: 'distinctHabits',
    target: 5,
  },
  {
    id: 'habit-10',
    title: 'Habit Builder',
    description: 'Complete a single habit ten times.',
    tier: 'free',
    metric: 'maxHabitCompletions',
    target: 10,
  },
  {
    id: 'perfect-week',
    title: 'Perfect Week',
    description: 'Finish every scheduled habit day in a single week.',
    tier: 'free',
    metric: 'perfectWeeks',
    target: 1,
  },
  {
    id: 'two-perfect-weeks',
    title: 'Double Perfect Week',
    description: 'Achieve two perfect weeks across your habits.',
    tier: 'free',
    metric: 'perfectWeeks',
    target: 2,
  },
  {
    id: 'thirty-completions',
    title: 'Thirty Day Momentum',
    description: 'Reach thirty scheduled habit completions.',
    tier: 'pro',
    metric: 'totalCompletions',
    target: 30,
  },
  {
    id: 'fifty-completions',
    title: 'Fifty Day Momentum',
    description: 'Reach fifty scheduled habit completions.',
    tier: 'pro',
    metric: 'totalCompletions',
    target: 50,
  },
  {
    id: 'seventy-five-completions',
    title: 'Seventy-Five Deep',
    description: 'Reach seventy-five scheduled habit completions.',
    tier: 'pro',
    metric: 'totalCompletions',
    target: 75,
  },
  {
    id: 'hundred-completions',
    title: 'Century Club',
    description: 'Stack up one hundred scheduled habit completions.',
    tier: 'pro',
    metric: 'totalCompletions',
    target: 100,
  },
  {
    id: 'one-fifty-completions',
    title: 'One-Fifty Strong',
    description: 'Reach one hundred fifty scheduled habit completions.',
    tier: 'pro',
    metric: 'totalCompletions',
    target: 150,
  },
  {
    id: 'two-hundred-completions',
    title: 'Two Hundred Club',
    description: 'Reach two hundred scheduled habit completions.',
    tier: 'pro',
    metric: 'totalCompletions',
    target: 200,
  },
  {
    id: 'three-hundred-completions',
    title: 'Three Hundred Club',
    description: 'Reach three hundred scheduled habit completions.',
    tier: 'pro',
    metric: 'totalCompletions',
    target: 300,
  },
  {
    id: 'year-of-wins',
    title: 'Year of Wins',
    description: 'Reach 365 scheduled habit completions.',
    tier: 'pro',
    metric: 'totalCompletions',
    target: 365,
  },
  {
    id: 'five-hundred-completions',
    title: 'Five Hundred Strong',
    description: 'Reach five hundred scheduled habit completions.',
    tier: 'pro',
    metric: 'totalCompletions',
    target: 500,
  },
  {
    id: 'seven-fifty-completions',
    title: 'Seven Fifty Focus',
    description: 'Reach seven hundred fifty scheduled habit completions.',
    tier: 'pro',
    metric: 'totalCompletions',
    target: 750,
  },
  {
    id: 'one-thousand-completions',
    title: 'One Thousand Days',
    description: 'Reach one thousand scheduled habit completions.',
    tier: 'pro',
    metric: 'totalCompletions',
    target: 1000,
  },
  {
    id: 'fifteen-hundred-completions',
    title: 'Fifteen Hundred',
    description: 'Reach one thousand five hundred scheduled habit completions.',
    tier: 'pro',
    metric: 'totalCompletions',
    target: 1500,
  },
  {
    id: 'two-thousand-completions',
    title: 'Two Thousand Strong',
    description: 'Reach two thousand scheduled habit completions.',
    tier: 'pro',
    metric: 'totalCompletions',
    target: 2000,
  },
  {
    id: 'twenty-one-days',
    title: 'Twenty-One Active Days',
    description: 'Complete habits on twenty-one separate calendar days.',
    tier: 'pro',
    metric: 'scheduledDays',
    target: 21,
  },
  {
    id: 'thirty-days-active',
    title: 'Thirty Active Days',
    description: 'Complete habits on thirty separate calendar days.',
    tier: 'pro',
    metric: 'scheduledDays',
    target: 30,
  },
  {
    id: 'sixty-days-active',
    title: 'Sixty Active Days',
    description: 'Complete habits on sixty separate calendar days.',
    tier: 'pro',
    metric: 'scheduledDays',
    target: 60,
  },
  {
    id: 'ninety-days-active',
    title: 'Ninety Active Days',
    description: 'Complete habits on ninety separate calendar days.',
    tier: 'pro',
    metric: 'scheduledDays',
    target: 90,
  },
  {
    id: 'one-twenty-days-active',
    title: 'One Twenty Active',
    description: 'Complete habits on 120 separate calendar days.',
    tier: 'pro',
    metric: 'scheduledDays',
    target: 120,
  },
  {
    id: 'one-eighty-days-active',
    title: 'One Eighty Active',
    description: 'Complete habits on 180 separate calendar days.',
    tier: 'pro',
    metric: 'scheduledDays',
    target: 180,
  },
  {
    id: 'year-active',
    title: 'Year of Active Days',
    description: 'Complete habits on 365 separate calendar days.',
    tier: 'pro',
    metric: 'scheduledDays',
    target: 365,
  },
  {
    id: 'five-hundred-active-days',
    title: 'Five Hundred Active Days',
    description: 'Complete habits on five hundred separate calendar days.',
    tier: 'pro',
    metric: 'scheduledDays',
    target: 500,
  },
  {
    id: 'twenty-one-streak',
    title: 'Twenty-One Day Streak',
    description: 'Hold a twenty-one day streak on any habit.',
    tier: 'pro',
    metric: 'longestStreak',
    target: 21,
  },
  {
    id: 'thirty-day-streak',
    title: 'Thirty Day Streak',
    description: 'Hold a thirty day streak on any habit.',
    tier: 'pro',
    metric: 'longestStreak',
    target: 30,
  },
  {
    id: 'forty-five-day-streak',
    title: 'Forty-Five Day Streak',
    description: 'Hold a forty-five day streak on any habit.',
    tier: 'pro',
    metric: 'longestStreak',
    target: 45,
  },
  {
    id: 'sixty-day-streak',
    title: 'Sixty Day Streak',
    description: 'Hold a sixty day streak on any habit.',
    tier: 'pro',
    metric: 'longestStreak',
    target: 60,
  },
  {
    id: 'ninety-day-streak',
    title: 'Ninety Day Streak',
    description: 'Hold a ninety day streak on any habit.',
    tier: 'pro',
    metric: 'longestStreak',
    target: 90,
  },
  {
    id: 'one-twenty-day-streak',
    title: 'One Twenty Day Streak',
    description: 'Hold a 120 day streak on any habit.',
    tier: 'pro',
    metric: 'longestStreak',
    target: 120,
  },
  {
    id: 'one-eighty-day-streak',
    title: 'One Eighty Day Streak',
    description: 'Hold a 180 day streak on any habit.',
    tier: 'pro',
    metric: 'longestStreak',
    target: 180,
  },
  {
    id: 'year-streak',
    title: 'Year-Long Streak',
    description: 'Hold a 365 day streak on any habit.',
    tier: 'pro',
    metric: 'longestStreak',
    target: 365,
  },
  {
    id: 'perfect-month',
    title: 'Perfect Month',
    description: 'Achieve four perfect weeks across your habits.',
    tier: 'pro',
    metric: 'perfectWeeks',
    target: 4,
  },
  {
    id: 'perfect-eight',
    title: 'Eight Perfect Weeks',
    description: 'Achieve eight perfect weeks across your habits.',
    tier: 'pro',
    metric: 'perfectWeeks',
    target: 8,
  },
  {
    id: 'perfect-twelve',
    title: 'Twelve Perfect Weeks',
    description: 'Achieve twelve perfect weeks across your habits.',
    tier: 'pro',
    metric: 'perfectWeeks',
    target: 12,
  },
  {
    id: 'perfect-sixteen',
    title: 'Sixteen Perfect Weeks',
    description: 'Achieve sixteen perfect weeks across your habits.',
    tier: 'pro',
    metric: 'perfectWeeks',
    target: 16,
  },
  {
    id: 'perfect-twenty-four',
    title: 'Twenty-Four Perfect Weeks',
    description: 'Achieve twenty-four perfect weeks across your habits.',
    tier: 'pro',
    metric: 'perfectWeeks',
    target: 24,
  },
  {
    id: 'perfect-thirty-six',
    title: 'Thirty-Six Perfect Weeks',
    description: 'Achieve thirty-six perfect weeks across your habits.',
    tier: 'pro',
    metric: 'perfectWeeks',
    target: 36,
  },
  {
    id: 'perfect-year',
    title: 'Fifty-Two Perfect Weeks',
    description: 'Achieve fifty-two perfect weeks across your habits.',
    tier: 'pro',
    metric: 'perfectWeeks',
    target: 52,
  },
  {
    id: 'perfect-two-years',
    title: 'Two Years Perfect',
    description: 'Achieve 104 perfect weeks across your habits.',
    tier: 'pro',
    metric: 'perfectWeeks',
    target: 104,
  },
  {
    id: 'seven-habits',
    title: 'Seven Habits Active',
    description: 'Complete seven different habits.',
    tier: 'pro',
    metric: 'distinctHabits',
    target: 7,
  },
  {
    id: 'ten-habits',
    title: 'Ten Habits Active',
    description: 'Complete ten different habits.',
    tier: 'pro',
    metric: 'distinctHabits',
    target: 10,
  },
  {
    id: 'twelve-habits',
    title: 'Twelve Habits Active',
    description: 'Complete twelve different habits.',
    tier: 'pro',
    metric: 'distinctHabits',
    target: 12,
  },
  {
    id: 'fifteen-habits',
    title: 'Fifteen Habits Active',
    description: 'Complete fifteen different habits.',
    tier: 'pro',
    metric: 'distinctHabits',
    target: 15,
  },
  {
    id: 'twenty-habits',
    title: 'Twenty Habits Active',
    description: 'Complete twenty different habits.',
    tier: 'pro',
    metric: 'distinctHabits',
    target: 20,
  },
  {
    id: 'twenty-five-habits',
    title: 'Twenty-Five Habits Active',
    description: 'Complete twenty-five different habits.',
    tier: 'pro',
    metric: 'distinctHabits',
    target: 25,
  },
  {
    id: 'habit-25',
    title: 'Habit Builder Pro',
    description: 'Complete a single habit twenty-five times.',
    tier: 'pro',
    metric: 'maxHabitCompletions',
    target: 25,
  },
  {
    id: 'habit-50',
    title: 'Habit Mastery',
    description: 'Complete a single habit fifty times.',
    tier: 'pro',
    metric: 'maxHabitCompletions',
    target: 50,
  },
  {
    id: 'habit-75',
    title: 'Habit Devotion',
    description: 'Complete a single habit seventy-five times.',
    tier: 'pro',
    metric: 'maxHabitCompletions',
    target: 75,
  },
  {
    id: 'habit-100',
    title: 'Habit Century',
    description: 'Complete a single habit one hundred times.',
    tier: 'pro',
    metric: 'maxHabitCompletions',
    target: 100,
  },
  {
    id: 'habit-150',
    title: 'Habit 150',
    description: 'Complete a single habit one hundred fifty times.',
    tier: 'pro',
    metric: 'maxHabitCompletions',
    target: 150,
  },
  {
    id: 'habit-200',
    title: 'Habit 200',
    description: 'Complete a single habit two hundred times.',
    tier: 'pro',
    metric: 'maxHabitCompletions',
    target: 200,
  },
  {
    id: 'habit-365',
    title: 'Habit 365',
    description: 'Complete a single habit 365 times.',
    tier: 'pro',
    metric: 'maxHabitCompletions',
    target: 365,
  },
  {
    id: 'habit-500',
    title: 'Habit 500',
    description: 'Complete a single habit five hundred times.',
    tier: 'pro',
    metric: 'maxHabitCompletions',
    target: 500,
  },
];

export const COMPLETION_MILESTONES: MilestoneDefinition[] = [
  { id: 'completions-7', label: '7 completions', type: 'completions', target: 7, tier: 'free' },
  { id: 'completions-30', label: '30 completions', type: 'completions', target: 30, tier: 'free' },
  {
    id: 'completions-100',
    label: '100 completions',
    type: 'completions',
    target: 100,
    tier: 'pro',
  },
];

export const PERFECT_WEEK_MILESTONES: MilestoneDefinition[] = [
  { id: 'perfect-weeks-1', label: 'Perfect week', type: 'perfectWeeks', target: 1, tier: 'free' },
  { id: 'perfect-weeks-4', label: '4 perfect weeks', type: 'perfectWeeks', target: 4, tier: 'pro' },
  {
    id: 'perfect-weeks-12',
    label: '12 perfect weeks',
    type: 'perfectWeeks',
    target: 12,
    tier: 'pro',
  },
];
